package ComercioElectronico.ejercicio2.domain;

import java.util.HashMap;

public class Carrito {

    private Long id;
    private Cliente cliente;
    private HashMap<Producto, Integer> productos;
    public HashMap<Producto, Integer> getProductos() {
        return this.productos;
    }


    private static Long autoGeneratedID = 0l;

    public Carrito(Cliente cliente) {
        this.id = autoGeneratedID();
        this.cliente = cliente;
        this.productos = new HashMap<>();
    }


    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Cliente getClient() {
        return this.cliente;
    }

    public void setClient(Cliente client) {
        this.cliente = client;
    }

    public HashMap<Producto,Integer> getOrder() {
        return this.productos;
    }

    public void setOrder(HashMap<Producto,Integer> order) {
        this.productos = order;
    }

    public void addProduct(Producto producto, int qty){
        if(producto.getStock() < qty){
            System.out.println("Solo quedan " + producto.getStock() + " productos en stock");
        } else if(productos.containsKey(producto)){
            modifyQty(producto, productos.get(producto) + qty);
        } else {
            productos.put(producto, qty);
            producto.comprar(qty);
        }
    }

    public void removeProduct(Producto producto){
        if (productos.containsKey(producto)){
            productos.remove(producto);
        } else {
            System.out.println("El producto no esta en su carrito");
        }
    }

    public void modifyQty(Producto producto, int qty){
        if(producto.getStock() < qty){
            System.out.println("Solo quedan " + producto.getStock() + " productos en stock");
        } else if (productos.containsKey(producto)){
            productos.put(producto, qty);
            producto.comprar(qty);
        } else {
            System.out.println("El producto no está en el carrito");
        }
    }

    private static Long autoGeneratedID(){
        return ++autoGeneratedID;
    }

    public void displayCart() {
        productos.forEach((key, value) -> System.out.println(key.getNombre() + " - cant: " + value));
    }

    public boolean isEmpty() {
        return productos.isEmpty();
    }

    public void clear() {
        productos.clear();
    }
}