package ComercioElectronico.ejercicio2.domain;

import java.util.HashMap;
import java.util.Map;

public class Carrito {

    private Long id;
    private Cliente cliente;
    private HashMap<Producto, Integer> productos;

    private static Long autoGeneratedID = 0l;

    public Carrito(Cliente cliente) {
        this.id = autoGeneratedID();
        this.cliente = cliente;
        this.productos = new HashMap<>();
    }

    public Long getId() {
        return this.id;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public HashMap<Producto, Integer> getProductos() {
        return this.productos;
    }

    private static Long autoGeneratedID(){
        return ++autoGeneratedID;
    }

    public void displayCart() {
        if (productos.isEmpty()) {
            System.out.println("El carrito está vacío.");
            return;
        }

        for (Map.Entry<Producto, Integer> entry : productos.entrySet()) {
            Producto producto = entry.getKey();
            Integer cantidad = entry.getValue();
            System.out.println(producto.getNombre() + " - $" + producto.getPrecio() + " - Cantidad: " + cantidad);
        }
    }
}
