package ComercioElectronico.ejercicio2.domain;

import java.util.HashMap;
import java.util.Map;

public class Carrito {
    private static long autoGeneratedID = 0;
    private long id;
    private Cliente cliente;
    private Map<Producto, Integer> productos;

    public static long generateNewId() {
        return ++autoGeneratedID;
    }

    public Carrito(long nuevoId, Cliente cliente) {
        this.id = generateNewId();
        this.cliente = cliente;
        this.productos = new HashMap<>();
    }

    public Long getId() {
      return this.id;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public HashMap<Producto, Integer> getProductos() {
        return (HashMap<Producto, Integer>) this.productos;
    }

    // En la clase Carrito
    private Pedido pedido;

    // Getter y Setter
    public Pedido getPedido() {
        return this.pedido;
    }

    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }

    public void displayCart() {
        if (productos.isEmpty()) {
            System.out.println("El carrito está vacío.");
            return;
        }

        for (Map.Entry<Producto, Integer> entry : productos.entrySet()) {
            Producto producto = entry.getKey();
            Integer cantidad = entry.getValue();
            System.out.println(producto.getNombre() + " - $" + producto.getPrecio() + " - Cantidad: " + cantidad);
        }
    }
}